import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { normalizeRoomCode } from './code-normalizer';

/**
 * Crockford base32 alphabet, excluding I, L, O, U.
 * 32 characters => ~1 billion possible 6-character codes.
 */
const CROCKFORD_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const CODE_LENGTH = 6;

/**
 * A small, conservative blocklist of 6-character strings that could be
 * generated by the Crockford alphabet and should not be shown to users.
 * Kept short so the retry loop is effectively free.
 */
const PROFANITY_BLOCKLIST = new Set([
  'FCK0FF',
  'FCK1NG',
  'FCKY0U',
  'SH1T',
  'B1TCH',
  'ASSH0L',
  'D1CK',
  'C0CK',
  'P0RN',
  'N1GGA',
  'N1GGER',
  'FAGG0T',
  'CUNT',
  'TWAT',
  'WANKER',
]);

const MAX_RETRIES = 10;

@Injectable()
export class CodeGeneratorService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generates a normalised 6-character room code and persists it on the
   * given session. Retries on profanity hits or unique-constraint
   * collisions (another waiting session already has the code).
   */
  async generateAndAssign(sessionId: string): Promise<string> {
    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      const raw = this.generateRaw();
      const code = normalizeRoomCode(raw);

      if (PROFANITY_BLOCKLIST.has(code)) {
        continue;
      }

      try {
        await this.prisma.session.update({
          where: { id: sessionId },
          data: { code },
        });
        return code;
      } catch (error) {
        const isUniqueViolation =
          error instanceof Prisma.PrismaClientKnownRequestError &&
          error.code === 'P2002';
        if (!isUniqueViolation) {
          throw error;
        }
        // Collision: try again with a fresh code.
      }
    }

    throw new Error(
      `Failed to generate a unique room code after ${MAX_RETRIES} attempts`,
    );
  }

  private generateRaw(): string {
    let result = '';
    for (let i = 0; i < CODE_LENGTH; i++) {
      const index = Math.floor(Math.random() * CROCKFORD_ALPHABET.length);
      result += CROCKFORD_ALPHABET[index];
    }
    return result;
  }
}
